/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d9dadc",
        background: "#f9f9fb",
        "on-tertiary-fixed": "#1c1b1b",
        "on-error-container": "#93000a",
        "surface-container-high": "#e8e8ea",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e2e4",
        "primary-fixed-dim": "#a1d494",
        "surface-container-highest": "#e2e2e4",
        outline: "#72796e",
        "on-surface": "#1a1c1d",
        "inverse-surface": "#2f3132",
        "on-background": "#1a1c1d",
        "on-secondary-fixed": "#221b00",
        secondary: "#705d00",
        "outline-variant": "#c2c9bb",
        "on-surface-variant": "#42493e",
        "surface-container": "#eeeef0",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f5",
        "on-primary-fixed-variant": "#23501e",
        "secondary-fixed": "#ffe16d",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-secondary-container": "#6e5c00",
        surface: "#f9f9fb",
        "tertiary-fixed": "#e5e2e1",
        "inverse-primary": "#a1d494",
        "on-tertiary-container": "#c5c2c2",
        "on-tertiary": "#ffffff",
        primary: "#154212",
        "secondary-container": "#fcd400",
        "surface-bright": "#f9f9fb",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#474646",
        "on-secondary-fixed-variant": "#544600",
        "tertiary-container": "#515050",
        "secondary-fixed-dim": "#e9c400",
        "inverse-on-surface": "#f0f0f2",
        error: "#ba1a1a",
        "primary-container": "#2d5a27",
        "on-primary-container": "#9dd090",
        "on-primary-fixed": "#002201",
        tertiary: "#3a3939",
        "primary-fixed": "#bcf0ae",
        "surface-tint": "#3b6934",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap-desktop": "120px",
        "grid-margin": "24px",
        base: "8px",
        "section-gap-mobile": "64px",
        "grid-gutter": "20px",
      },
      fontFamily: {
        "headline-md": ["Literata", "serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Literata", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Literata", "serif"],
        "display-lg": ["Literata", "serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
